logging:
  level:
    root: error
    com.mishinyura.books: info
    org.springframework.jdbc.core: debug
  file.name: logs/application.log

spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/books?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    sql-migration-prefix: P
    driver-class-name: org.postgresql.Driver
