spring:
  main:
    banner-mode: off
  banner:
    image:
      location: banner.txt
  profiles:
    active: dev-h2
  #    active: dev-postgres
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8080
