CREATE TABLE users
(
    id    BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO users(username, password)
VALUES('q', '$2a$12$J18i1MV9yf5rKASG.5v6gO7WPsyar3GZwgzCW7pVZA3..ikfuiMZa');
